name: tastymeals
description: "A cross-platform recipe application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.18.0
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
