version: "3"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
    expose:
       - 5432
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./db
        target: /db

  server:
    image: 'public.ecr.aws/o6b6o8s4/tastymeals:latest'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:

volumes:
  db-data:
